---
title: 'Anexo 1: Visualizaciones de respuestas'
author: "Mauricio Vazquez"
date: '2024-11-28'
output:
  pdf_document: default
  html_document: default
---

***Link del repositorio de GitHub: https://github.com/MauricioVazquezM/Multivariate_Statistical_Course_Assignments_Fall2024***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, fig.width=10)

# Libraries
library(MASS)  
library(ggplot2)
library(GGally)
library(mclust)
library(kableExtra)
library(FactoMineR)
library(knitr)
library(caret)
library(dplyr)
library(gridExtra)
library(ggfortify)
library(copula)
```

## Q1: Analisis de componentes principales (PCA)

```{r fig.align='center', fig.width=5, fig.height=3, echo=FALSE}
# Especifica la ruta al archivo
file_path <- "C:\\Users\\mauva\\OneDrive\\Documents\\ITAM\\9no Semestre\\METODOS MULTIVARIADOS\\REPOSITORIO\\Multivariate_Statistical_Course_Assignments_Fall2024\\EXAM 02\\turtles.rda"

# Carga el archivo .rda
load(file_path)

# Variables numéricas
numerical_vars <- turtles[, c("length", "width", "height")]

# PCA
pca_result <- prcomp(numerical_vars, scale. = TRUE)

# Resumen del PCA
summary(pca_result)

# Añadir la variable 'sex' para colorear por sexo
projected_data <- data.frame(pca_result$x, sex = turtles$sex)

# Gráfico
ggplot(projected_data, aes(x = PC1, y = PC2, color = sex)) +
  geom_point(size = 3, alpha = 0.7) +
  labs(
    title = "Primeras 2 Componentes Principales",
    x = "Primera Componente Principal (PC1)",
    y = "Segunda Componente Principal (PC2)",
    color = "Sexo"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "right"
  )
```


\newpage

## Q2: Cópula Clayton

```{r fig.align='center', fig.width=5, fig.height=3, echo=FALSE}
set.seed(42) 
# Parámetro de theta
theta <- 2  

# Cópula de Clayton
clayton_copula <- claytonCopula(param = theta, dim = 2)

# Simulando datos
n <- 1000  
simulated_data <- rCopula(n, clayton_copula)

# Pasando a un dataframe
data <- data.frame(x = simulated_data[, 1], y = simulated_data[, 2])

# Graficando
ggplot(data, aes(x = x, y = y)) +
  geom_point(alpha = 0.5, color = "blue") +
  geom_density_2d(color = "red") + 
  labs(
    title = "Simulación de una Cópula Clayton",
    x = "Variable 1",
    y = "Variable 2"
  ) +
  theme_minimal()

# Curvas de contorno
ggplot(data, aes(x = x, y = y)) +
  geom_density_2d_filled(contour_var = "density", alpha = 0.6) +
  labs(title = "Curvas de Contorno - Cópula de Clayton",
       x = "Variable 1",
       y = "Variable 2") +
  theme_minimal()

# Mostrar ambos gráficos en un solo layout
#grid.arrange(a, b, ncol = 2)
```


\newpage

## Q3: Escalamiento multidimensional
